### ISSUE TITLE
Retriever Inference Time

### ISSUE THREAD

**Issue by ashispapu** [efficientqa/retrieval-based-baselines#2]
Thanks for the great work and making it available to us. I could set up and run the DPR system with pre-trained models. However I observed it takes more than 20 seconds to fetch top 10 passages from the end to end system for a given query. I'm using the faiss package which is integrated with the retriever. Am I missing something here ? If this is the case, is there any way to reduce the inference time to make it effective in real time QA applications.

Looking forward to your valuable feedback.

**Comment by shmsw25** [comment]
Hi @ashispapu, thanks for your interest. Hmm, it shouldn't take that long to query the top k passages. Were you running [run_inference.py](https://github.com/efficientqa/retrieval-based-baselines/blob/master/run_inference.py)? I wonder if you could check if latency comes from indexing (specifically, [this line](https://github.com/facebookresearch/DPR/blob/master/dpr/indexer/faiss_indexers.py#L92)) by printing some logs before and after this line. Please let me know which lines cause latency.

Another option you can consider is to build a hierarchical index by specifying `--hnsw_index`. We didn't provide this index but you can generate it by following the instruction in README. It takes much longer to build this index, but it reduces the latency for the inference.

**Comment by ashispapu** [comment]
Hi @shmsw25 Thanks for the response. I'll try and let you know the latency comes from indexing. Could you share  the time usually it takes to fetch top 10 passages based on your observation.

**Comment by shmsw25** [comment]
Hi @ashispapu, I just checked - searching for 1000 questions took 10 seconds to me.
```python3
index = faiss.read_index(index_path)
qvec = np.ndarray(1000*768, dtype="float32").reshape(1000, 768)
t = time.time()
index.search(qvec, 100)
print ("searching for 1000 questions: %.2s" % (time.time()-t))
```
Also, querying one by one instead of batch took way more. Do you need to query one by one, or is using batch fine? If you need to query one by one, using hierarchical index seems to be unavoidable. Actually it is pretty straightforward - when you make inference [here](https://github.com/efficientqa/retrieval-based-baselines#dpr-retrieval), you can specify `--hnsw_index`. It will then save hierarchical index so that you can load it instead of the Flat Index next time.

**Comment by ashispapu** [comment]
Hi @shmsw25 I have checked the latency and it takes most of the time in  `index.search_knn()` function. I tried with 2 to 100 number of passages and in all cases it takes 21-23 secs to get the passages. 
As per you suggestion, tried making `hnsw_index=True` with the existing index, however getting  an error.

`query_nhsw_vectors = np.hstack((query_vectors, aux_dim.reshape(-1, 1)))`
query_hnsw_vectors (2, 769)  --> Since the dimension of the query vector changes from 768 to 769 in hierarchical index class. Do you have any suggestion to make it work .

Thank you.

**Comment by shmsw25** [comment]
Hi @ashispapu. You will have to build a new HNSW index instead of using the flat index that was released, i.e. you need to re-do step 3 of [this part](https://github.com/efficientqa/retrieval-based-baselines#dpr-retrieval) with `hnsw_index=True` and different path for saving index.

**Comment by shmsw25** [comment]
Side note: as mentioned in [this issue](https://github.com/facebookresearch/DPR/issues/30), HNSW Index takes a lot of memory, so can't say it's suitable for this competition. But if it's for other purposes, you can try!

**Comment by ashispapu** [comment]
Thanks @shmsw25 . Would explore and see if it helps for the task.
